### ISSUE TITLE
App crashes

### ISSUE THREAD

**Issue by vidhyagithub** [fdchiu/SNPECam#1]
Hi,

Thanks for the application.

When I ran this application on Google Pixel2 deice, it crashes quoting below error message.

"Unable to create native Tensor" - It is happened when the application tried to execute the model using "mNNNetwork.execute(inputs) 

May I have your opinion on this please? I am unable to trace down the root cause for the same.

**Comment by ghost** [comment]
Try deleting or commenting out CaffeSSD {......} in buld.gradle(Module: app). CaffeSSD is not working.

**Comment by zorrobyte** [comment]
I commented out CaffeSSD and still crashes

2019-09-20 12:07:10.996 28149-28195/com.davidchiu.snpe E/com.davidchiu.snpe: vendor/qcom/proprietary/commonsys-intf/adsprpc/src/apps_std_imp.c:729:Error 45: fopen failed for testsig-0x3256cf24.so. (No such file or directory)
2019-09-20 12:07:10.997 28149-28195/com.davidchiu.snpe E/com.davidchiu.snpe: vendor/qcom/proprietary/commonsys-intf/adsprpc/src/apps_std_imp.c:729:Error 45: fopen failed for testsig.so. (No such file or directory)
2019-09-20 12:07:11.014 28149-28149/com.davidchiu.snpe V/com.davidchiu.snpe: vendor/qcom/proprietary/commonsys-intf/adsprpc/src/fastrpc_apps_user.c:1029: remote_handle64_open: Successfully opened handle 0xfee4cb50 for file:///libsnpe_dsp_v65_domains_skel.so?snpe_dsp_domains_skel_handle_invoke&_modver=1.0&_dom=cdsp on domain 3
2019-09-20 12:07:11.015 28149-28149/com.davidchiu.snpe D/snpe-android: Building SNPE instance...
2019-09-20 12:07:11.410 28149-28149/com.davidchiu.snpe E/adsprpc: src/rpcmem_android.c:284::error: -1: 0 <= ioctl(rpcmem_ionfd, ION_IOC_ALLOC_KK, &alloc)
2019-09-20 12:07:11.410 28149-28149/com.davidchiu.snpe E/adsprpc: src/rpcmem_android.c:158:rpcmem jb allocation error: -1: trying ics
2019-09-20 12:07:11.410 28149-28149/com.davidchiu.snpe E/adsprpc: src/rpcmem_android.c:329::error: -1: 0 <= ioctl(rpcmem_ionfd, ION_IOC_ALLOC_ICS, &alloc)
2019-09-20 12:07:11.410 28149-28149/com.davidchiu.snpe E/adsprpc: src/rpcmem_android.c:159::error: -1: 0 == (nErr = rpcmem_contig_alloc_ics(m, heap_mask, size, &po))
2019-09-20 12:07:11.411 28149-28149/com.davidchiu.snpe D/snpe-android: Built SNPE instance...
2019-09-20 12:07:11.411 28149-28149/com.davidchiu.snpe D/snpe-android: Network pool updated, added [0x0] count: 0
2019-09-20 12:07:11.414 28149-28149/com.davidchiu.snpe E/SNPENet: Unable to create network! Cause: error_code=401; error_message=Network creation has failed. Unable to allocate DSP network descriptor.; error_component=Dl Network; line_no=141; thread_id=509553157448
    java.lang.IllegalStateException: Unable to create network! Cause: error_code=401; error_message=Network creation has failed. Unable to allocate DSP network descriptor.; error_component=Dl Network; line_no=141; thread_id=509553157448
        at com.qualcomm.qti.snpe.internal.NativeNetwork.nativeInitFromBuffer(Native Method)
        at com.qualcomm.qti.snpe.internal.NativeNetwork.<init>(NativeNetwork.java:67)
        at com.qualcomm.qti.snpe.SNPE$NeuralNetworkBuilder.build(SNPE.java:248)
        at com.davidchiu.snpecam.SNPENet.init(SNPENet.java:121)
        at com.davidchiu.snpecam.DetectorActivity.onPreviewSizeChosen(DetectorActivity.java:188)
        at com.davidchiu.snpecam.CameraActivity$5.onPreviewSizeChosen(CameraActivity.java:364)
        at com.davidchiu.snpecam.CameraConnectionFragment.setUpCameraOutputs(CameraConnectionFragment.java:399)
        at com.davidchiu.snpecam.CameraConnectionFragment.openCamera(CameraConnectionFragment.java:406)
        at com.davidchiu.snpecam.CameraConnectionFragment.access$000(CameraConnectionFragment.java:62)
        at com.davidchiu.snpecam.CameraConnectionFragment$1.onSurfaceTextureAvailable(CameraConnectionFragment.java:93)
        at android.view.TextureView.getTextureLayer(TextureView.java:398)
        at android.view.TextureView.draw(TextureView.java:343)
        at android.view.View.updateDisplayListIfDirty(View.java:19275)
        at android.view.View.draw(View.java:20128)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4349)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4128)
        at android.view.View.updateDisplayListIfDirty(View.java:19266)
        at android.view.View.draw(View.java:20128)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4349)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4128)
        at android.view.View.draw(View.java:20403)
        at android.view.View.updateDisplayListIfDirty(View.java:19275)
        at android.view.View.draw(View.java:20128)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4349)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4128)
        at android.view.View.updateDisplayListIfDirty(View.java:19266)
        at android.view.View.draw(View.java:20128)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4349)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4128)
        at android.view.View.updateDisplayListIfDirty(View.java:19266)
        at android.view.View.draw(View.java:20128)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4349)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4128)
        at android.view.View.draw(View.java:20403)
        at com.android.internal.policy.DecorView.draw(DecorView.java:781)
        at android.view.View.updateDisplayListIfDirty(View.java:19275)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:690)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:696)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:805)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:3712)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3502)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2856)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1810)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8084)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1312)
        at android.view.Choreographer.doCallbacks(Choreographer.java:1123)
        at android.view.Choreographer.doFrame(Choreographer.java:941)
        at android.view.Choreographer$FrameHandler.handleMessage(Choreographer.java:1227)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:7029)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2019-09-20 12:07:11.414 28149-28149/com.davidchiu.snpe D/AndroidRuntime: Shutting down VM
2019-09-20 12:07:11.415 28149-28149/com.davidchiu.snpe E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.davidchiu.snpe, PID: 28149
    java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Set com.qualcomm.qti.snpe.NeuralNetwork.getInputTensorsNames()' on a null object reference
        at com.davidchiu.snpecam.SNPENet.init(SNPENet.java:129)
        at com.davidchiu.snpecam.DetectorActivity.onPreviewSizeChosen(DetectorActivity.java:188)
        at com.davidchiu.snpecam.CameraActivity$5.onPreviewSizeChosen(CameraActivity.java:364)
        at com.davidchiu.snpecam.CameraConnectionFragment.setUpCameraOutputs(CameraConnectionFragment.java:399)
        at com.davidchiu.snpecam.CameraConnectionFragment.openCamera(CameraConnectionFragment.java:406)
        at com.davidchiu.snpecam.CameraConnectionFragment.access$000(CameraConnectionFragment.java:62)
        at com.davidchiu.snpecam.CameraConnectionFragment$1.onSurfaceTextureAvailable(CameraConnectionFragment.java:93)
        at android.view.TextureView.getTextureLayer(TextureView.java:398)
        at android.view.TextureView.draw(TextureView.java:343)
        at android.view.View.updateDisplayListIfDirty(View.java:19275)
        at android.view.View.draw(View.java:20128)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4349)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4128)
        at android.view.View.updateDisplayListIfDirty(View.java:19266)
        at android.view.View.draw(View.java:20128)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4349)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4128)
        at android.view.View.draw(View.java:20403)
        at android.view.View.updateDisplayListIfDirty(View.java:19275)
        at android.view.View.draw(View.java:20128)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4349)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4128)
        at android.view.View.updateDisplayListIfDirty(View.java:19266)
        at android.view.View.draw(View.java:20128)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4349)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4128)
        at android.view.View.updateDisplayListIfDirty(View.java:19266)
        at android.view.View.draw(View.java:20128)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4349)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4128)
        at android.view.View.draw(View.java:20403)
        at com.android.internal.policy.DecorView.draw(DecorView.java:781)
        at android.view.View.updateDisplayListIfDirty(View.java:19275)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:690)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:696)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:805)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:3712)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3502)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2856)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1810)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8084)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1312)
        at android.view.Choreographer.doCallbacks(Choreographer.java:1123)
        at android.view.Choreographer.doFrame(Choreographer.java:941)
        at android.view.Choreographer$FrameHandler.handleMessage(Choreographer.java:1227)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:7029)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2019-09-20 12:07:11.422 28149-28589/com.davidchiu.snpe D/OSTracker: OS Event: crash
2019-09-20 12:07:11.429 28149-28589/com.davidchiu.snpe D/AbstractTracker: Event success

**Comment by ghost** [comment]
You need a device with Snapdragon Processor. It will not run on other device as it uses Snapdragon-Neural-Processing-Engine (SNPE). Please check your device. **Network pool updated, added [0x0] count: 0** (Count should be 1)

**Comment by zorrobyte** [comment]
Hello @SimranMarok 

This is on a OnePlus 7 pro which I run SNPE on. I'm switching to x86, android is too hard for rapid ML iteration.

Good luck!

**Comment by fdchiu** [comment]
Hi Vidhya,
Sorry for the late reply. Please make sure you are running the code on a
supported QCOM chipset based android phone.

Let me know how it goes!

David

**Comment by fdchiu** [comment]
Will do!

Thanks!

David

**Comment by fdchiu** [comment]
Hi Ross,

Sorry for the late reply. Please make sure you are running the code on a
supported QCOM chipset based android phone.

Let me know how it goes!

David
